version: '3.8'

services:
  reverse-proxy:
    # build: .
    image: tataabancens/reverse-proxy:1.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./modsecurity.conf:/etc/nginx/modsecurity.conf
      - ./rules:/etc/nginx/rules
    depends_on:
      - backend

  backend:
    # image: ac1197298bd4 # Usa la imagen de tu servidor backend
    # build:
    #   context: ./juice-shop
    #   dockerfile: Dockerfile
    image: tataabancens/juice-shop:1.0
    ports:
      - "3000:3000"
