version: '3.8'

services:
  webapp1:
    image: tataabancens/juice-shop:1.0
    ports:
      - "3000:3000"
  
  webapp2:
    image: ghcr.io/digininja/dvwa:latest
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    ports:
      - "4280:80"

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    restart: unless-stopped

  reverse-proxy:
    image: tataabancens/reverse-proxy:1.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./modsecurity.conf:/etc/nginx/modsecurity.conf
      - ./rules:/etc/nginx/rules
    depends_on:
      - webapp1
      - webapp2
